In [0]:
import tensorflow as tf
tf.enable_eager_execution()

In [0]:
layer = tf.keras.layers.Dense(100)

layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [11]:
layer(tf.zeros([10, 5]))

<tf.Tensor: id=88, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [12]:
layer.variables

[<tf.Variable 'dense_3/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.6267112 ,  0.42995304, -0.6259527 ,  0.5306079 , -0.09666973,
          0.502255  ,  0.3775832 ,  0.07565135, -0.58868355,  0.27244705],
        [ 0.04191333, -0.19518661, -0.54917496,  0.21272594, -0.42463416,
         -0.1462605 , -0.1921565 , -0.1389929 , -0.5481968 ,  0.26666307],
        [-0.14688009,  0.04776907,  0.21281493,  0.45169944, -0.5548659 ,
         -0.06454074,  0.04334539,  0.26069832,  0.14403272, -0.6230451 ],
        [ 0.33690548,  0.47944897, -0.42633912,  0.3826459 , -0.561569  ,
         -0.335647  , -0.40110758, -0.1520879 , -0.03960478, -0.48396575],
        [-0.5208589 ,  0.4378448 , -0.34123057, -0.16637757, -0.47015604,
         -0.3107131 ,  0.56465465,  0.61819464, -0.5127739 , -0.29590666]],
       dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [13]:
layer.kernel, layer.bias

(<tf.Variable 'dense_3/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.6267112 ,  0.42995304, -0.6259527 ,  0.5306079 , -0.09666973,
          0.502255  ,  0.3775832 ,  0.07565135, -0.58868355,  0.27244705],
        [ 0.04191333, -0.19518661, -0.54917496,  0.21272594, -0.42463416,
         -0.1462605 , -0.1921565 , -0.1389929 , -0.5481968 ,  0.26666307],
        [-0.14688009,  0.04776907,  0.21281493,  0.45169944, -0.5548659 ,
         -0.06454074,  0.04334539,  0.26069832,  0.14403272, -0.6230451 ],
        [ 0.33690548,  0.47944897, -0.42633912,  0.3826459 , -0.561569  ,
         -0.335647  , -0.40110758, -0.1520879 , -0.03960478, -0.48396575],
        [-0.5208589 ,  0.4378448 , -0.34123057, -0.16637757, -0.47015604,
         -0.3107131 ,  0.56465465,  0.61819464, -0.5127739 , -0.29590666]],
       dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [14]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs
    
  def build(self, input_shape):
    self.kernel = self.add_variable("kernel",
                                   shape=[int(input_shape[-1]),
                                          self.num_outputs])
    
  def call(self, input):
    return tf.matmul(input, self.kernel)
  
layer = MyDenseLayer(10)
print(layer(tf.zeros([10, 5])))
print(layer.trainable_variables)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'my_dense_layer_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.10116655,  0.6067062 , -0.19998321, -0.48352635,  0.32667732,
        -0.23413256,  0.1159879 ,  0.19511676, -0.373833  , -0.20266393],
       [-0.536913  ,  0.49828142, -0.15595806,  0.52225536, -0.29448774,
        -0.02620447,  0.35179198, -0.5457753 , -0.51602566, -0.5091767 ],
       [ 0.0125612 ,  0.15463322,  0.44834715, -0.39885297,  0.45688206,
         0.149342  , -0.6074586 ,  0.29561728, -0.610174  , -0.2977261 ],
       [ 0.15549046, -0.5815069 , -0.42234185,  0.07157069, -0.17653716,
         0.13980353,  0.16410398, 

In [18]:
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name='')
    filters1, filters2, filters3 = filters
    
    self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()
    
    self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()
    
    self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()
    
  def call(self, input_tensor, training= False) :
    
    x= self.conv2a(input_tensor)
    x= self.bn2a(x, training=training)
    x= tf.nn.relu(x)
    
    x= self.conv2b(x)
    x= self.bn2b(x, training=training)
    x= tf.nn.relu(x)
    
    x= self.conv2c(x)
    x= self.bn2c(x, training=training)
    
    x+= input_tensor
    return tf.nn.relu(x)
  
block = ResnetIdentityBlock(1, [1,2,3])
print (block(tf.zeros([1,2,3,3])))
print ([x.name for x in block.trainable_variables])

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block_5/conv2d_2/kernel:0', 'resnet_identity_block_5/conv2d_2/bias:0', 'resnet_identity_block_5/batch_normalization_2/gamma:0', 'resnet_identity_block_5/batch_normalization_2/beta:0', 'resnet_identity_block_5/conv2d_3/kernel:0', 'resnet_identity_block_5/conv2d_3/bias:0', 'resnet_identity_block_5/batch_normalization_3/gamma:0', 'resnet_identity_block_5/batch_normalization_3/beta:0', 'resnet_identity_block_5/conv2d_4/kernel:0', 'resnet_identity_block_5/conv2d_4/bias:0', 'resnet_identity_block_5/batch_normalization_4/gamma:0', 'resnet_identity_block_5/batch_normalization_4/beta:0']


In [20]:
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1,1)),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(2, 1,
                                                   padding='same'),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(3, (1, 1)),
                             tf.keras.layers.BatchNormalization()])

my_seq(tf.zeros([1, 2,3, 3]))

<tf.Tensor: id=573, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>