This is an introductory tutorial for using TensorFlow. It will cover:

Importing required packages

Creating and using Tensors

Using GPU acceleration

Datasets

In [0]:
import tensorflow as tf
tf.enable_eager_execution()


In [2]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))
print(tf.encode_base64("Hello World"))

print(tf.square(2) + tf.square(3))


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'SGVsbG8gV29ybGQ', shape=(), dtype=string)
tf.Tensor(13, shape=(), dtype=int32)


In [3]:
x = tf.matmul([[1]], [[2, 3]])
print(x.shape)
print(x.dtype)


(1, 2)
<dtype: 'int32'>


In [7]:
import numpy as np

ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)

print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor. numpy())

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [8]:
x = tf.random_uniform([3, 3])

print("Is there a GPU available: "),
print(tf.test.is_gpu_available())

print("Is the Tensoron GPU #0: ")
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
False
Is the Tensoron GPU #0: 
False


In [13]:
import time

def time_matmul(x):
  start = time.time()
  for loop in range(10):
    tf.matmul(x, x)
    
  result = time.time()-start
  
  print("10 loops: {:0.2f}%".format(1000*result))
  
print("On CPU:")
with tf.device("CPU:0"):
  x = tf.random_uniform([1000, 1000])
  assert x.device.endswith("CPU:0")
  time_matmul(x)
  
if tf.test.is_gpu_available():
  with tf.device("GPU:0"):
    x = tf.random_uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)
    

On CPU:
10 loops: 213.68%


In [0]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write(""" Line1
  Line 2
  Line 3
    """)
  
  ds_file = tf.data.TextLineDataset(filename)

In [0]:
ds_tensor = ds_tensors.map(tf.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)


In [18]:
print('/nElements in ds_file:')
for x in ds_tensors:
  print(x)
  
print('/nElements in ds_file:')
for x in ds_file:
  print(x)
  

/nElements in ds_file:
Instructions for updating:
Colocations handled automatically by placer.
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
/nElements in ds_file:
tf.Tensor([b' Line1' b'  Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'  Line 3' b'    '], shape=(2,), dtype=string)
